---
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/services/backend"
    schedule:
      interval: "weekly"
    target-branch: "main"
    ignore:
      -dependency-name: "django"
        update-type: ["version-update:semver-major"]
      -dependency-name: "graphene"
        update-type: ["version-update:semver-major"]
      -dependency-name: "graphene-django"
        update-type: ["version-update:semver-major"]
  - package-ecosystem: "pip"
    directory: "/services/measurements"
    schedule:
      interval: "weekly"
    target-branch: "main"
    reviewers:
      - "raoul-thill"
