---
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/services/backend"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    reviewers:
      - "raoul-thill"
  - package-ecosystem: "pip"
    directory: "/services/measurements"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    reviewers:
      - "raoul-thill"
